[pytest]
markers =
    regression: marks tests as regression tests
    smoke: marks tests as smoke tests

addopts = --html=reports/regression_report.html
          --self-contained-html
          --alluredir=reports/allure-results
          -v